Cb 8 zip code api
Codubee/ExploreCitiesTTH4-6 pull request #14
Opened 2020-12-17 23:22 UTC by Aarushi-Pandey

* **Please check if the PR fulfills these requirements**
- [ ] The pull request title contains the ticket number in the title. For example [CB-1]

* **What kind of change does this PR introduce?** (Bug fix, new feature...)
calls zipcode API using a supplied zip code

* **What is the current behavior?What does the code do before you made the new changes?** 
Currently, the application does not call the zipcode api.

* **What is the new behavior?**
The application calls the zipcode api and returns a json of the data from localhost8080.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR? Run a new command?)
Add the weather api key to the .env file

* **Other information**:

2020-12-19 22:10 UTC, Codubee commented
Hey Arushi. I think there are some changes in here that are not part of the zip code api

2020-12-20 23:30 UTC, JerryTeng01 reviewed
Seems good, just make sure to include the changes from main

2020-12-20 23:30 UTC, JerryTeng01 commented on backend/index.js
> +    console.log('Zipcode API is up and running')
change this since zip code api is not the only api running

2020-12-20 23:30 UTC, JerryTeng01 commented on backend/index.js
> +
you can get the parameters from req.query instead of hardcoding them

2020-12-20 23:30 UTC, JerryTeng01 commented on backend/index.js
> +    const headers = {headers: {authorization: process.env.API_KEY}}
change the name of the API key to something that describes what it is since there will be multiple api keys

2020-12-20 23:30 UTC, JerryTeng01 commented on backend/index.js
> +    const headers = {headers: {authorization: process.env.API_KEY}}
does this API actually require a key? It doesnt seem like it does

2020-12-27 20:38 UTC, Codubee commented on frontend/src/components/UserInput/Zipcode/Zipcode.js
> +import React from 'react'
Is this file part of this pr?

2020-12-27 20:38 UTC, Codubee commented on frontend/src/components/UserInput/Zipcode/Zipcode.css
> +.container {
Is this file part of this pr?

2020-12-27 20:38 UTC, Codubee commented on frontend/src/components/UserInput/UserInput.js
> +import React from 'react'
Is this file part of this pr?

2020-12-27 20:38 UTC, Codubee commented on frontend/src/App.js
>  import './App.css';
Is this file part of this pr?

2020-12-27 20:38 UTC, Codubee commented on frontend/package.json
>    "version": "0.1.0",
Is this file part of this pr?

2020-12-27 20:39 UTC, Codubee requested changes
There are some files for the frontend when I dont think there should be. Might consider removing them from this pr

2020-12-28 04:47 UTC, Aarushi-Pandey commented
Thanks so much for the detailed feedback Miguel and Jerry! It really helped me improve my code efficiently and quickly. I've updated this branch so that there are no merge conflicts with main and have changed my hardcoded zipcode and distance values in index.js to query parameters as Jerry suggested. Great job in figuring out that there was no need for the API key for the zipcode API as well! I've removed that as well. I've attempted to remove frontend files from this pr too. Please let me know if there are further changes to be made! Thanks once more for taking the time to give me detailed comments and suggestions :)

2020-12-28 06:54 UTC, Codubee commented on backend/index.js
> +    axios.get('https://www.zipcodeapi.com/rest/radius.json/'+zipcode+'/'+distance+'/km')
Can we use miles instead of kilometers

2020-12-28 06:55 UTC, Codubee requested changes
Fantastic work fixing everything! Just left one comment and then ill approve.

2020-12-28 22:16 UTC, Aarushi-Pandey commented
Changed distance from kilometers to miles.

2020-12-30 17:22 UTC, Codubee approved these changes

2020-12-30 17:22 UTC, merged